var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,h="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(h){const {createRequire:a}=await ((m)=>import(m))("module");var require=a(import.meta.url)}var l=(a,b)=>{throw b;},fa=import.meta.url,m;
if(h){var fs=require("fs"),ha=require("path");fa.startsWith("file:")&&ha.dirname(require("url").fileURLToPath(fa));m=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};process.argv.slice(2);l=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea){try{new URL(".",fa)}catch{}ea&&(m=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)})}
var ja=console.log.bind(console),u=console.error.bind(console),ka,v,w=!1,y,z,A,la,ma,B,na,oa,pa,ia=a=>a.startsWith("file://");function qa(){var a=v.buffer;z=new Int8Array(a);la=new Int16Array(a);f.HEAPU8=A=new Uint8Array(a);new Uint16Array(a);f.HEAP32=ma=new Int32Array(a);B=new Uint32Array(a);na=new Float32Array(a);pa=new Float64Array(a);oa=new BigInt64Array(a);new BigUint64Array(a)}var D=0,E=null;
function F(a){f.onAbort?.(a);a="Aborted("+a+")";u(a);w=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var ra;async function sa(a){if(!ArrayBuffer.isView(a))if(a==ra&&ka)a=new Uint8Array(ka);else if(m)a=m(a);else throw"both async and sync fetching of the wasm failed";return a}async function ta(a){var b=ra;try{var c=await sa(b);return await WebAssembly.instantiate(c,a)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),F(d)}}
async function ua(a){return ta(a)}class va{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var wa=a=>{for(;0<a.length;)a.shift()(f)},xa=[],za=[],Aa=()=>{var a=f.preRun.shift();za.push(a)},Ba=a=>{if(h)return a=Buffer.from(a,"base64"),new Uint8Array(a.buffer,a.byteOffset,a.length);for(var b,c,d=0,e=0,g=a.length,k=new Uint8Array((3*g>>2)-("="==a[g-2])-("="==a[g-1]));d<g;d+=4,e+=3)b=H[a.charCodeAt(d+1)],c=H[a.charCodeAt(d+2)],k[e]=H[a.charCodeAt(d)]<<2|b>>4,k[e+1]=b<<4|c>>2,k[e+2]=c<<6|H[a.charCodeAt(d+3)];return k},Ca=!0,Da=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,
1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ea=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Da(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Fa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ga=()=>{if(h){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},
Ha=a=>{(Ha=Ga())(a)},Ia=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Da(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ja="undefined"!=typeof TextDecoder?new TextDecoder:void 0,I=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&
128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ka=[],La=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ma=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=
a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},Na=[];function Oa(a,b){Na[a]={input:[],output:[],D:b};Pa(a,Qa)}
var Qa={open(a){var b=Na[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close(a){a.tty.D.fsync(a.tty)},fsync(a){a.tty.D.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.D.O)throw new J(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.D.O(a.tty)}catch(n){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.D.L)throw new J(60);try{for(var e=0;e<d;e++)a.tty.D.L(a.tty,b[c+e])}catch(g){throw new J(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ra={O(){a:{if(!Ka.length){var a=null;if(h){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(La(a)+1);a=Ma(a,b,0,b.length);b.length=a;Ka=b}a=Ka.shift()}return a},L(a,b){null===b||
10===b?(ja(I(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ja(I(a.output)),a.output=[])},ga(){return{$:25856,ba:5,Z:191,aa:35387,Y:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ha(){return 0},ia(){return[24,80]}},Sa={L(a,b){null===b||10===b?(u(I(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(u(I(a.output)),a.output=[])}},K={s:null,v(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||4096===(c&61440))throw new J(63);K.s||(K.s={dir:{node:{A:K.h.A,u:K.h.u,lookup:K.h.lookup,G:K.h.G,rename:K.h.rename,unlink:K.h.unlink,rmdir:K.h.rmdir,readdir:K.h.readdir,symlink:K.h.symlink},stream:{o:K.l.o}},file:{node:{A:K.h.A,u:K.h.u},stream:{o:K.l.o,read:K.l.read,write:K.l.write,R:K.l.R,T:K.l.T}},link:{node:{A:K.h.A,u:K.h.u,readlink:K.h.readlink},stream:{}},M:{node:{A:K.h.A,u:K.h.u},stream:Ta}});c=Ua(a,b,c,d);16384===(c.mode&61440)?(c.h=K.s.dir.node,c.l=K.s.dir.stream,c.g={}):32768===
(c.mode&61440)?(c.h=K.s.file.node,c.l=K.s.file.stream,c.m=0,c.g=null):40960===(c.mode&61440)?(c.h=K.s.link.node,c.l=K.s.link.stream):8192===(c.mode&61440)&&(c.h=K.s.M.node,c.l=K.s.M.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.g[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},fa(a){return a.g?a.g.subarray?a.g.subarray(0,a.m):new Uint8Array(a.g):new Uint8Array(0)},h:{A(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&
61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.m:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},u(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.m!=b&&(0==b?(a.g=null,a.m=0):(c=a.g,a.g=new Uint8Array(b),c&&a.g.set(c.subarray(0,Math.min(b,a.m))),a.m=b)))},lookup(){throw K.N;},G(a,b,c,d){return K.createNode(a,
b,c,d)},rename(a,b,c){try{var d=Va(b,c)}catch(g){}if(d){if(16384===(a.mode&61440))for(var e in d.g)throw new J(55);e=Wa(d.parent.id,d.name);if(L[e]===d)L[e]=d.C;else for(e=L[e];e;){if(e.C===d){e.C=d.C;break}e=e.C}}delete a.parent.g[a.name];b.g[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.g[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Va(a,b),d;for(d in c.g)throw new J(55);delete a.g[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.g)]},
symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},l:{read(a,b,c,d,e){var g=a.node.g;if(e>=a.node.m)return 0;a=Math.min(a.node.m-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===z.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.g||a.g.subarray)){if(g)return a.g=b.subarray(c,c+d),a.m=d;if(0===a.m&&0===e)return a.g=
b.slice(c,c+d),a.m=d;if(e+d<=a.m)return a.g.set(b.subarray(c,c+d),e),d}g=e+d;var k=a.g?a.g.length:0;k>=g||(g=Math.max(g,k*(1048576>k?2:1.125)>>>0),0!=k&&(g=Math.max(g,256)),k=a.g,a.g=new Uint8Array(g),0<a.m&&a.g.set(k.subarray(0,a.m),0));if(a.g.subarray&&b.subarray)a.g.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.g[e+g]=b[c+g];a.m=Math.max(a.m,e+d);return d},o(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.m);if(0>b)throw new J(28);return b},R(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new J(43);a=a.node.g;if(e&2||!a||a.buffer!==z.buffer){d=!0;F();e=void 0;if(!e)throw new J(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{ka:e,X:d}},T(a,b,c,d){K.l.write(a,b,0,d,c,!1);return 0}}},Xa=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ya=null,Za={},M=[],$a=1,L=null,ab=!1,bb=!0,cb={},J=class{name="ErrnoError";constructor(a){this.B=a}},db=class{F={};node=null;get flags(){return this.F.flags}set flags(a){this.F.flags=
a}get position(){return this.F.position}set position(a){this.F.position=a}},eb=class{h={};l={};H=null;constructor(a,b,c,d){a||=this;this.parent=a;this.v=a.v;this.id=$a++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function N(a,b={}){if(!a)throw new J(44);b.J??(b.J=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=Ya,e="/",g=0;g<a.length;g++){var k=g===a.length-1;if(k&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Fa(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");continue a}else d=d.parent;else{e=Ea(e+"/"+a[g]);try{d=Va(d,a[g])}catch(n){if(44===n?.B&&k&&b.V)return{path:e};throw n;}!d.H||k&&!b.J||(d=d.H.root);if(40960===(d.mode&61440)&&(!k||b.I)){if(!d.h.readlink)throw new J(52);
d=d.h.readlink(d);"/"===d.charAt(0)||(d=Fa(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function Wa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%L.length}function Va(a,b){var c=16384===(a.mode&61440)?(c=fb(a,"x"))?c:a.h.lookup?0:2:54;if(c)throw new J(c);for(c=L[Wa(a.id,b)];c;c=c.C){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.lookup(a,b)}
function Ua(a,b,c,d){a=new eb(a,b,c,d);b=Wa(a.parent.id,a.name);a.C=L[b];return L[b]=a}function gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function fb(a,b){if(bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function hb(a,b){if(16384!==(a.mode&61440))return 54;try{return Va(a,b),20}catch(c){}return fb(a,"wx")}function O(a){a=M[a];if(!a)throw new J(8);return a}
function ib(a,b=-1){a=Object.assign(new db,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!M[b])break a;throw new J(33);}a.fd=b;return M[b]=a}function jb(a,b){var c=null?.l.u,d=c?null:a;c??=a.h.u;if(!c)throw new J(63);c(d,b)}var Ta={open(a){a.l=Za[a.node.rdev].l;a.l.open?.(a)},o(){throw new J(70);}};function Pa(a,b){Za[a]={l:b}}
function kb(a,b){var c="/"===b;if(c&&Ya)throw new J(10);if(!c&&b){var d=N(b,{J:!1});b=d.path;d=d.node;if(d.H)throw new J(10);if(16384!==(d.mode&61440))throw new J(54);}b={type:a,ja:{},S:b,U:[]};a=a.v(b);a.v=b;b.root=a;c?Ya=a:d&&(d.H=b,d.v&&d.v.U.push(b))}function lb(a,b,c){var d=N(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new J(28);if("."===a||".."===a)throw new J(20);var e=hb(d,a);if(e)throw new J(e);if(!d.h.G)throw new J(63);return d.h.G(d,a,b,c)}
function P(a){return lb(a,16895,0)}function mb(a,b,c){"undefined"==typeof c&&(c=b,b=438);lb(a,b|8192,c)}function nb(a,b){if(!Ia(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=hb(c,b);if(d)throw new J(d);if(!c.h.symlink)throw new J(63);c.h.symlink(c,b,a)}
function ob(a,b,c=438){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=N(a,{I:!(b&131072),V:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=lb(a,c|511,0);g=!0}if(!d)throw new J(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new J(54);
if(!g&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==gb(b)||b&576)?31:fb(d,gb(b)):44))throw new J(e);if(b&512&&!g){e=d;e="string"==typeof e?N(e,{I:!0}).node:e;if(16384===(e.mode&61440))throw new J(31);if(32768!==(e.mode&61440))throw new J(28);var k=fb(e,"w");if(k)throw new J(k);jb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.v.S;var n=n?"/"!==e[e.length-1]?`${e}/${n}`:e+n:e;break a}n=n?`${e.name}/${n}`:e.name;e=e.parent}n=ib({node:d,path:n,flags:b,
seekable:!0,position:0,l:d.l,W:[],error:!1});n.l.open&&n.l.open(n);g&&(c&=511,d="string"==typeof d?N(d,{I:!0}).node:d,jb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),da:void 0}));!f.logReadFiles||b&1||a in cb||(cb[a]=1);return n}function pb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.l.o)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.l.o(a,b,c);a.W=[]}
function Q(a,b,c){a=Ea("/dev/"+a);var d=Xa(!!b,!!c);Q.P??(Q.P=64);var e=Q.P++<<8|0;Pa(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,k,n,q){for(var p=0,C=0;C<q;C++){try{var r=b()}catch(t){throw new J(29);}if(void 0===r&&0===p)throw new J(6);if(null===r||void 0===r)break;p++;k[n+C]=r}p&&(g.node.atime=Date.now());return p},write(g,k,n,q){for(var p=0;p<q;p++)try{c(k[n+p])}catch(C){throw new J(29);}q&&(g.node.mtime=g.node.ctime=Date.now());return p}});mb(a,d,e)}
for(var U={},qb=void 0,rb=0,V={},sb=a=>{y=a;Ca||0<rb||(f.onExit?.(a),w=!0);l(a,new va(a))},tb=a=>{if(!w)try{if(a(),!(Ca||0<rb))try{y=a=y,sb(a)}catch(b){b instanceof va||"unwind"==b||l(1,b)}}catch(b){b instanceof va||"unwind"==b||l(1,b)}},ub=[],W,X,vb=[],H=new Uint8Array(123),Y=25;0<=Y;--Y)H[48+Y]=52+Y,H[65+Y]=Y,H[97+Y]=26+Y;H[43]=62;H[47]=63;L=Array(4096);kb(K,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");Pa(259,{read:()=>0,write:(d,e,g,k)=>k,o:()=>0});mb("/dev/null",259);Oa(1280,Ra);Oa(1536,Sa);mb("/dev/tty",1280);mb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ha(a),b=a.byteLength);return a[--b]};Q("random",c);Q("urandom",c);P("/dev/shm");P("/dev/shm/tmp")})();
(function(){P("/proc");var a=P("/proc/self");P("/proc/self/fd");kb({v(){var b=Ua(a,"fd",16895,73);b.l={o:K.l.o};b.h={lookup(c,d){c=+d;var e=O(c);c={parent:null,v:{S:"fake"},h:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(M.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();K.N=new J(44);K.N.stack="<generic error, no stack>";f.noExitRuntime&&(Ca=f.noExitRuntime);f.print&&(ja=f.print);f.printErr&&(u=f.printErr);f.wasmBinary&&(ka=f.wasmBinary);
f.addFunction=(a,b)=>{if(!X){X=new WeakMap;var c=W.length;if(X)for(var d=0;d<0+c;d++){var e;(e=ub[d])||(ub[d]=e=W.get(d));e&&X.set(e,d)}}if(c=X.get(a)||0)return c;if(vb.length)c=vb.pop();else{try{W.grow(1)}catch(q){if(!(q instanceof RangeError))throw q;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=W.length-1}try{d=c,W.set(d,a),ub[d]=W.get(d)}catch(q){if(!(q instanceof TypeError))throw q;if("function"==typeof WebAssembly.Function){var g=WebAssembly.Function;d={i:"i32",j:"i64",f:"f32",
d:"f64",e:"externref",p:"i32"};e={parameters:[],results:"v"==b[0]?[]:[d[b[0]]]};for(var k=1;k<b.length;++k)e.parameters.push(d[b[k]]);b=new g(e,a)}else{d=[1];e=b.slice(0,1);b=b.slice(1);k={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);var n=b.length;128>n?d.push(n):d.push(n%128|128,n>>7);for(g of b)d.push(k[g]);"v"==e?d.push(0):d.push(1,k[e]);b=[0,97,115,109,1,0,0,0,1];g=d.length;128>g?b.push(g):b.push(g%128|128,g>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}g=c;W.set(g,b);ub[g]=W.get(g)}X.set(a,c);return c};f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return z[a];case "i8":return z[a];case "i16":return la[a>>1];case "i32":return ma[a>>2];case "i64":return oa[a>>3];case "float":return na[a>>2];case "double":return pa[a>>3];case "*":return B[a>>2];default:F(`invalid type for getValue: ${b}`)}};f.UTF8ToString=(a,b)=>a?I(A,a,b):"";f.stringToUTF8=(a,b,c)=>Ma(a,A,b,c);
f.lengthBytesUTF8=La;
var xb={__syscall_dup:function(a){try{var b=O(a),c=ib(b,-1);c.l?.ea?.(c);return c.fd}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.B}},__syscall_openat:function(a,b,c,d){qb=d;try{b=b?I(A,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":O(a).path;if(0==e.length)throw new J(44);b=g+"/"+e}if(d){var k=ma[+qb>>2];qb+=4;var n=k}else n=0;return ob(b,c,n).fd}catch(q){if("undefined"==typeof U||"ErrnoError"!==q.name)throw q;return-q.B}},_abort_js:()=>F(""),_emscripten_runtime_keepalive_clear:()=>
{Ca=!1;rb=0},_setitimer_js:(a,b)=>{V[a]&&(clearTimeout(V[a].id),delete V[a]);if(!b)return 0;var c=setTimeout(()=>{delete V[a];tb(()=>wb(a,performance.now()))},b);V[a]={id:c,la:b};return 0},emscripten_date_now:()=>Date.now(),emscripten_resize_heap:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-v.buffer.byteLength+65535)/65536|0;try{v.grow(d);qa();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},exit:a=>{y=a;sb(a)},fd_close:function(a){try{var b=O(a);if(null===b.fd)throw new J(8);b.K&&(b.K=null);try{b.l.close&&b.l.close(b)}catch(c){throw c;}finally{M[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.B}},fd_read:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,k=b=0;k<c;k++){var n=B[a>>2],q=B[a+4>>2];a+=8;var p=e,C=n,r=q,t=g,ya=z;if(0>r||0>t)throw new J(28);if(null===p.fd)throw new J(8);if(1===(p.flags&2097155))throw new J(8);
if(16384===(p.node.mode&61440))throw new J(31);if(!p.l.read)throw new J(28);var R="undefined"!=typeof t;if(!R)t=p.position;else if(!p.seekable)throw new J(70);var S=p.l.read(p,ya,C,r,t);R||(p.position+=S);var x=S;if(0>x){var T=-1;break a}b+=x;if(x<q)break;"undefined"!=typeof g&&(g+=x)}T=b}B[d>>2]=T;return 0}catch(G){if("undefined"==typeof U||"ErrnoError"!==G.name)throw G;return G.B}},fd_seek:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=
O(a);pb(e,b,c);oa[d>>3]=BigInt(e.position);e.K&&0===b&&0===c&&(e.K=null);return 0}catch(g){if("undefined"==typeof U||"ErrnoError"!==g.name)throw g;return g.B}},fd_write:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,k=b=0;k<c;k++){var n=B[a>>2],q=B[a+4>>2];a+=8;var p=e,C=n,r=q,t=g,ya=z;if(0>r||0>t)throw new J(28);if(null===p.fd)throw new J(8);if(0===(p.flags&2097155))throw new J(8);if(16384===(p.node.mode&61440))throw new J(31);if(!p.l.write)throw new J(28);p.seekable&&p.flags&1024&&pb(p,0,2);
var R="undefined"!=typeof t;if(!R)t=p.position;else if(!p.seekable)throw new J(70);var S=p.l.write(p,ya,C,r,t,void 0);R||(p.position+=S);var x=S;if(0>x){var T=-1;break a}b+=x;if(x<q)break;"undefined"!=typeof g&&(g+=x)}T=b}B[d>>2]=T;return 0}catch(G){if("undefined"==typeof U||"ErrnoError"!==G.name)throw G;return G.B}},proc_exit:sb},Z=await (async function(){function a(d){Z=d.exports;v=Z.memory;qa();W=Z.__indirect_function_table;D--;f.monitorRunDependencies?.(D);0==D&&E&&(d=E,E=null,d());
return Z}D++;f.monitorRunDependencies?.(D);var b={env:xb,wasi_snapshot_preview1:xb};if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{d(a(e,g))})});ra??=Ba("");try{var c=await ua(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}());f._xmlResetLastError=Z.xmlResetLastError;f._xmlGetLastError=Z.xmlGetLastError;f._xmlCtxtParseDtd=Z.xmlCtxtParseDtd;f._xmlCtxtReadMemory=Z.xmlCtxtReadMemory;f._xmlCtxtSetErrorHandler=Z.xmlCtxtSetErrorHandler;
f._xmlNewInputFromMemory=Z.xmlNewInputFromMemory;f._xmlFreeParserCtxt=Z.xmlFreeParserCtxt;f._xmlNewParserCtxt=Z.xmlNewParserCtxt;f._xmlInitParser=Z.xmlInitParser;f._xmlNewNs=Z.xmlNewNs;f._xmlSetNs=Z.xmlSetNs;f._xmlFreeDtd=Z.xmlFreeDtd;f._xmlFreeNode=Z.xmlFreeNode;f._xmlGetIntSubset=Z.xmlGetIntSubset;f._xmlNewDoc=Z.xmlNewDoc;f._xmlFreeDoc=Z.xmlFreeDoc;f._xmlRemoveProp=Z.xmlRemoveProp;f._xmlNewNode=Z.xmlNewNode;f._xmlNewDocNode=Z.xmlNewDocNode;f._xmlNewReference=Z.xmlNewReference;
f._xmlNewDocTextLen=Z.xmlNewDocTextLen;f._xmlNewCDataBlock=Z.xmlNewCDataBlock;f._xmlNewDocComment=Z.xmlNewDocComment;f._xmlAddNextSibling=Z.xmlAddNextSibling;f._xmlAddPrevSibling=Z.xmlAddPrevSibling;f._xmlAddChild=Z.xmlAddChild;f._xmlUnlinkNode=Z.xmlUnlinkNode;f._xmlNodeGetContent=Z.xmlNodeGetContent;f._xmlDocGetRootElement=Z.xmlDocGetRootElement;f._xmlDocSetRootElement=Z.xmlDocSetRootElement;f._xmlSetNsProp=Z.xmlSetNsProp;f._xmlNodeSetContentLen=Z.xmlNodeSetContentLen;f._xmlGetNsList=Z.xmlGetNsList;
f._xmlSearchNs=Z.xmlSearchNs;f._xmlHasNsProp=Z.xmlHasNsProp;f._xmlSetWinPathEnabled=Z.xmlSetWinPathEnabled;f._xmlCtxtValidateDtd=Z.xmlCtxtValidateDtd;f._xmlOutputBufferClose=Z.xmlOutputBufferClose;f._xmlOutputBufferCreateIO=Z.xmlOutputBufferCreateIO;f._xmlRegisterInputCallbacks=Z.xmlRegisterInputCallbacks;f._xmlCleanupInputCallbacks=Z.xmlCleanupInputCallbacks;f._xmlC14NExecute=Z.xmlC14NExecute;f._xmlSaveSetIndentString=Z.xmlSaveSetIndentString;f._xmlSaveToIO=Z.xmlSaveToIO;f._xmlSaveDoc=Z.xmlSaveDoc;
f._xmlSaveTree=Z.xmlSaveTree;f._xmlSaveClose=Z.xmlSaveClose;f._xmlRelaxNGFree=Z.xmlRelaxNGFree;f._xmlRelaxNGNewDocParserCtxt=Z.xmlRelaxNGNewDocParserCtxt;f._xmlRelaxNGFreeParserCtxt=Z.xmlRelaxNGFreeParserCtxt;f._xmlRelaxNGParse=Z.xmlRelaxNGParse;f._xmlRelaxNGSetParserStructuredErrors=Z.xmlRelaxNGSetParserStructuredErrors;f._xmlRelaxNGNewValidCtxt=Z.xmlRelaxNGNewValidCtxt;f._xmlRelaxNGFreeValidCtxt=Z.xmlRelaxNGFreeValidCtxt;f._xmlRelaxNGSetValidStructuredErrors=Z.xmlRelaxNGSetValidStructuredErrors;
f._xmlRelaxNGValidateDoc=Z.xmlRelaxNGValidateDoc;f._xmlSchemaFree=Z.xmlSchemaFree;f._xmlSchemaNewDocParserCtxt=Z.xmlSchemaNewDocParserCtxt;f._xmlSchemaFreeParserCtxt=Z.xmlSchemaFreeParserCtxt;f._xmlSchemaFreeValidCtxt=Z.xmlSchemaFreeValidCtxt;f._xmlSchemaParse=Z.xmlSchemaParse;f._xmlSchemaSetParserStructuredErrors=Z.xmlSchemaSetParserStructuredErrors;f._xmlSchemaSetValidStructuredErrors=Z.xmlSchemaSetValidStructuredErrors;f._xmlSchemaNewValidCtxt=Z.xmlSchemaNewValidCtxt;
f._xmlSchemaValidateOneElement=Z.xmlSchemaValidateOneElement;f._xmlSchemaValidateDoc=Z.xmlSchemaValidateDoc;f._xmlXIncludeNewContext=Z.xmlXIncludeNewContext;f._xmlXIncludeFreeContext=Z.xmlXIncludeFreeContext;f._xmlXIncludeSetErrorHandler=Z.xmlXIncludeSetErrorHandler;f._xmlXIncludeProcessNode=Z.xmlXIncludeProcessNode;f._xmlXPathFreeCompExpr=Z.xmlXPathFreeCompExpr;f._xmlXPathFreeObject=Z.xmlXPathFreeObject;f._xmlXPathRegisterNs=Z.xmlXPathRegisterNs;f._xmlXPathNewContext=Z.xmlXPathNewContext;
f._xmlXPathFreeContext=Z.xmlXPathFreeContext;f._xmlXPathCtxtCompile=Z.xmlXPathCtxtCompile;f._xmlXPathCompiledEval=Z.xmlXPathCompiledEval;f._xmlXPathSetContextNode=Z.xmlXPathSetContextNode;var wb=Z._emscripten_timeout;f._malloc=Z.malloc;f._free=Z.free;
function yb(){function a(){f.calledRun=!0;if(!w){if(!f.noFSInit&&!ab){var b,c;ab=!0;b??=f.stdin;c??=f.stdout;d??=f.stderr;b?Q("stdin",b):nb("/dev/tty","/dev/stdin");c?Q("stdout",null,c):nb("/dev/tty","/dev/stdout");d?Q("stderr",null,d):nb("/dev/tty1","/dev/stderr");ob("/dev/stdin",0);ob("/dev/stdout",1);ob("/dev/stderr",1)}Z.__wasm_call_ctors();bb=!1;aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var d=f.postRun.shift();xa.push(d)}wa(xa)}}
if(0<D)E=yb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();wa(za);0<D?E=yb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();yb();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
