/**
 * @file Automatically generated by barrelsby.
 */

export * from "./lib/run-cli";
export * from "./lib/types";
export * from "./lib/xml-helpers";
export * from "./scripts/comment";
export * from "./scripts/office/pack";
export * from "./scripts/office/unpack";
export * from "./scripts/office/validate";
export * from "./scripts/office/helpers/merge-runs";
export * from "./scripts/office/helpers/simplify-redlines";
export * from "./scripts/office/validators/base";
export * from "./scripts/office/validators/docx-diagnostics";
export * from "./scripts/office/validators/docx";
export * from "./scripts/office/validators/pptx";
export * from "./scripts/office/validators/redlining";
