/**
 * @file Public barrel. Auto-generated by barrelsby plus the four-class
 * surface from `docs/superpowers/specs/2026-05-29-four-class-architecture-design.md`.
 */

// Existing surface (preserved verbatim from the auto-generated barrel).
export * from "./lib/run-cli";
export * from "./lib/types";
export * from "./lib/xml-helpers";
export * from "./scripts/comment";
export * from "./scripts/office/pack";
export * from "./scripts/office/unpack";
export * from "./scripts/office/validate";
export * from "./scripts/office/helpers/merge-runs";
export * from "./scripts/office/helpers/simplify-redlines";
export * from "./scripts/office/validators/base";
export * from "./scripts/office/validators/docx-diagnostics";
export * from "./scripts/office/validators/docx";
export * from "./scripts/office/validators/pptx";
export * from "./scripts/office/validators/redlining";

// Four-class surface (PR C tasks C.1–C.5).
export { Validate } from "./validate";
export type { ValidateOptions } from "./validate";
export { Repair } from "./repair";
export type { RepairOptions, RepairResult } from "./repair";
export { Normalize } from "./normalize";
export type { NormalizeResult } from "./normalize";
export { Measure } from "./measure";
export type {
  MeasureOptions,
  MeasureResult,
  MeasureClassification,
  MeasureMetrics,
  AstAdapter,
} from "./measure";

import { Validate } from "./validate";
import { Repair } from "./repair";
import { Normalize } from "./normalize";
import { Measure } from "./measure";

/**
 * Functional helpers — the eventual `jubarte.*` shape once jubarte-first
 * consumes docx-validate (spec §7 reserves the `read` / `write` slots for
 * the jubarte-first AST hub). The four functions here mirror the four
 * top-level classes for the 90% use case where consumers don't need to
 * configure an `XsdValidator` or other options.
 */
export const jubarte = {
  validate: (bytes: Uint8Array) => new Validate().run(bytes),
  repair: (bytes: Uint8Array) => new Repair().run(bytes),
  normalize: (bytes: Uint8Array) => new Normalize().run(bytes),
  measure: (bytes: Uint8Array) => new Measure().runOne(bytes),
} as const;
